import { Cars } from './app/shared/models/Cars';

export const sample_cars: Cars[] = [
  {
    id:'1',
    name: 'Nissan GTR R-34',
    madeYear: '1998-2002',
    price: 250_000,
    favorite: true,
    origins: ['Japan'],
    imageUrl: 'assets/r34.jpg',
    tags: ['Godzilla'],
  },
  {
    id:'2',
    name: 'Toyota Supra MK4',
    price: 260_000,
    madeYear: '1998-2002',
    favorite: true,
    origins: ['Japan'],
    imageUrl: 'assets/supra_mk4.jpg',
    tags: ['Supra'],
  },
  {
    id:'3',
    name: 'BMW M3 E46',
    price: 100_000,
    madeYear: '2000-2006',
    favorite: true,
    origins: ['Germany'],
    imageUrl: 'assets/m3_e46.jpg',
    tags: [],
  },
  {
    id:'4',
    name: 'BMW M5 CS',
    price: 146_000,
    madeYear: '2021',
    favorite: true,
    origins: ['Germany'],
    imageUrl: 'assets/m5_cs.jpg',
    tags: ['Monster'],
  },
  {
    id:'5',
    name: 'Mercedes AMG GTR',
    price: 165_000,
    madeYear: '2017-2021',
    favorite: true,
    origins: ['Germany'],
    imageUrl: 'assets/amg_gtr.jpg',
    tags: [],
  },
  {
    id:'6',
    name: 'Audi RS7',
    price: 120_000,
    madeYear: '2021- ',
    favorite: false,
    origins: ['Germany'],
    imageUrl: 'assets/rs7.jpg',
    tags: [],
  }
]
